[uwsgi]
uid = searxng
gid = searxng
workers = 4
threads = 4
plugin = python3
lazy-apps = true
module = searx.webapp
virtualenv = /usr/local/searxng/
pythonpath = /usr/local/searxng/
chdir = /usr/local/searxng/searx/
master = true
disable-logging = true
http = 0.0.0.0:8080
